kind: pipeline
type: docker
name: default

trigger:
  branch:
    - master
    - restructuring

clone:
  disable: true

steps:
  - name: clone
    image: drone/git
    commands:
      - git clone http://192.168.1.101:3000/kcbimonte/Treasury-MK3_API.git .
      - git checkout $DRONE_COMMIT

  - name: build
    image: mcr.microsoft.com/dotnet/sdk:5.0
    commands: 
      - ls
      - dotnet build

  - name: publish
    image: plugins/docker
    settings:
      tags: [ "${DRONE_COMMIT_SHA:0:7}","latest" ]
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kbimonte/treasury-api
      context: Treasury.WebAPI/
      dockerfile: Treasury.WebAPI/Dockerfile