kind: pipeline
type: docker
name: default

trigger:
  branch:
    - master

clone:
  disable: true

steps:
  - name: clone
    image: drone/git
    commands:
      - git clone http://192.168.1.101:3000/kcbimonte/Treasury-MK3_API.git .

  - name: build
    image: mcr.microsoft.com/dotnet/sdk:5.0
    commands: 
      - dotnet build

  - name: publish
    image: plugins/docker
    settings:
      dockerfile: Treasury/Dockerfile
      tags: [ "${DRONE_COMMIT_SHA:0:7}","latest" ]
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: kbimonte/treasury-api